### ISSUE TITLE
Make the title more readable over the bike lane image on the main page

### ISSUE THREAD

**Issue by moorepants** [moorepants/icsc2017.ucdavis.edu#5]

**Comment by moorepants** [comment]
This can be added to the styles.css for improvement:
```css
section.site-slider h1 {
	text-shadow: 3px 3px 4px #fff;
}
section.site-slider h3 {
	text-shadow: 2px 2px 3px #000;
	font-weight: bold !important;
}
section.site-slider p {
	text-shadow: 2px 2px 1px #fff;
}
```

Also in layout.css in the vertoh theme disable line 1049:

```css
section.fullwidth.site-slider .slider-content h3 {
    font-size: 26px;
    /* font-weight: normal !important; */
    margin-bottom: 3px;
}
```

**Comment by moorepants** [comment]
With white for all the text colors, darkened background image, and this css:
```css
section.site-slider h1 {
	text-shadow: 3px 3px 4px #000;
}
section.site-slider h3 {
	text-shadow: 2px 2px 3px #000;
	font-weight: bold !important;
}
section.site-slider p {
	text-shadow: 1px 1px 1px #000;
	font-weight: bold !important;
}
```
I get:
![selection_081](https://cloud.githubusercontent.com/assets/276007/21403384/6bd1176c-c771-11e6-9d1b-d58ef3677f0c.jpg)
